### ISSUE TITLE
Large media query does not display properly in some components

### ISSUE THREAD

**Issue by dptty** [roopemerikukka/yfd-website#68]
https://github.com/roopemerikukka/yfd-website/blob/b16f57eb37b2e287cc811a9122f91d5407113499/components/featuredProductCard.js#L74-L99

https://github.com/roopemerikukka/yfd-website/blob/b16f57eb37b2e287cc811a9122f91d5407113499/components/featuredPullUp.js#L36-L40

**Comment by sarukuku** [comment]
The large breakpoint for the `featuredPullUp.js` works on my computer. Addition to it rendering correctly I inspected the generated css by hand and it is also correct.
<img width="1680" alt="screenshot 2018-07-26 14 34 27" src="https://user-images.githubusercontent.com/1204559/43260313-beeb4586-90e1-11e8-8ba9-7638c6905f63.png">

**Comment by sarukuku** [comment]
With the `featuredProductCard.js` the generated css is corrupt. The media queries look something like this:
```css
@media screen and (min-width.jsx-708216323:64em) .featured-product-card__img.jsx-708216323{
    -webkit-order:1;
    -ms-flex-order:1;
    order:1;
}
```

That's far from correct.
